Repository Co-Drive/Driver-Client, pull requests merged in 2024-09, with the labels that each got.

#169 [ Register ] 회원가입 뷰 api 연결
  src/components/Register/NickName.tsx
  src/libs/apis/Register/patchProfile.ts
  src/libs/apis/Register/postNickname.ts
  src/page/RegisterPage.tsx
  src/types/Register/RegisterType.tsx
Labels: 🐬 문주, 🚀 api, 📋 register

#182 [ MyProfile ] 마이페이지 뷰 퍼블리싱
  src/assets/icon/ic_minus_white.svg
  src/assets/icon/ic_revise.svg
  src/assets/index.ts
  src/components/MyProfile/FollowingList.tsx
  src/components/MyProfile/MyGoal.tsx
  src/components/MyProfile/Profile.tsx
  src/components/MyProfile/ProfileEdit.tsx
  src/page/MyProfilePage.tsx
  src/styles/style.d.ts
  src/types/MyProfile/MyProfileType.tsx
Labels: 🐬 문주, 🖼️ publishing, profile

#175 [ Group-All ] 그룹 뷰 수정 (디자인 반영)
  src/Router.tsx
  src/assets/icon/ic_filter.svg
  src/assets/icon/ic_group_filter.svg
  src/assets/icon/ic_search.svg
  src/assets/index.ts
  src/components/GroupAll/GroupItem.tsx
  src/components/GroupAll/GroupRecommend.tsx
  src/components/GroupAll/groupFilter/LanguageSelectBox.tsx
  src/components/GroupAll/groupFilter/RangeSlidrFilter.tsx
  src/components/GroupAll/groupFilter/SearchBar.tsx
  src/constants/GroupAll/groupAllConst.ts
  src/page/GroupAllPage.tsx
  src/types/GroupAll/GroupAllType.tsx
Labels: 🐬 문주, 🖼️ publishing, group-all

#177 [ Home ] Home API 부분 연결
  src/common/CommonMonthSolve.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Home/TodaySolve.tsx
  src/components/Home/WeekFollowing/ProfileCard.tsx
  src/components/Home/WeekFollowing/WeeklyFollower.tsx
  src/components/Home/WeekRate.tsx
  src/libs/apis/Home/getFollowingsCheck.ts
  src/libs/apis/Home/getMonthSolve.ts
  src/libs/apis/Home/getUserAchieve.ts
  src/libs/apis/Solution/getMonthlySolution.ts
  src/libs/hooks/Home/useGetFollowingsCheck.ts
  src/libs/hooks/Home/useGetMonthSolve.ts
  src/libs/hooks/Home/useGetUserAchieve.ts
  src/types/Home/calendarType.ts
  src/types/Home/getMonthSolveTypes.ts
  src/types/Home/todaySolveType.ts
  src/types/Week/HomeFollowerTypes.ts
Labels: 🐡 승택, 🏠 home, 🚀 api

#168 [ Home ] 주간성과율 및 주간팔로잉 현황 부분 퍼블리싱
  src/common/CommonMonthSolve.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/CustomCalendar.tsx
  src/components/Home/HomeHeader.tsx
  src/components/Home/TodaySolve.tsx
  src/components/Home/WeekFollowing/ProfileCard.tsx
  src/components/Home/WeekFollowing/WeeklyFollower.tsx
  src/components/Home/WeekRate.tsx
  src/components/Home/WeekRateCustomLabel.tsx
  src/constants/Home/follwerConst.ts
  src/libs/apis/Home/getFollowingsCheck.ts
  src/libs/apis/Home/getMonthSolve.ts
  src/libs/apis/Home/getUserAchieve.ts
  src/libs/apis/Solution/getMonthlySolution.ts
  src/libs/hooks/Home/useGetFollowingsCheck.ts
  src/libs/hooks/Home/useGetMonthSolve.ts
  src/libs/hooks/Home/useGetUserAchieve.ts
  src/page/Home.tsx
  src/types/Home/calendarType.ts
  src/types/Home/getMonthSolveTypes.ts
  src/types/Home/todaySolveType.ts
  src/types/Week/HomeFollowerTypes.ts
  src/types/Week/weekRateTypes.ts
  yarn.lock
Labels: 🐡 승택, 🏠 home, 🖼️ publishing

#188 [ Deploy ] feat/home -> develop 머지
  src/assets/btn/btn_information.svg
  src/assets/icon/ic_home_Header.svg
  src/assets/index.ts
  src/common/CommonMonthSolve.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/CustomCalendar.tsx
  src/components/Home/HomeHeader.tsx
  src/components/Home/TodaySolve.tsx
  src/components/Home/WeekFollowing/ProfileCard.tsx
  src/components/Home/WeekFollowing/WeeklyFollower.tsx
  src/components/Home/WeekRate.tsx
  src/components/Home/WeekRateCustomLabel.tsx
  src/components/PageLayout/PageLayout.tsx
  src/constants/Home/follwerConst.ts
  src/libs/apis/Home/getFollowingsCheck.ts
  src/libs/apis/Home/getMonthSolve.ts
  src/libs/apis/Home/getUserAchieve.ts
  src/libs/apis/Solution/getMonthlySolution.ts
  src/libs/hooks/Home/useGetFollowingsCheck.ts
  src/libs/hooks/Home/useGetMonthSolve.ts
  src/libs/hooks/Home/useGetUserAchieve.ts
  src/page/Home.tsx
  src/types/Home/calendarType.ts
  src/types/Home/getMonthSolveTypes.ts
  src/types/Home/todaySolveType.ts
  src/types/Week/HomeFollowerTypes.ts
  src/types/Week/weekRateTypes.ts
  yarn.lock
Labels: 🐡 승택, 🏠 home, 👨‍🎤 deploy

#181 [ QA-rooming ] 기본적인 디자인/ 로직 관련 qa 반영
  src/assets/btn/btn_heart.svg
  src/assets/icon/ic_calendar.svg
  src/assets/index.ts
  src/common/CodeSpace/Memo.tsx
  src/common/CommonUserList.tsx
  src/common/SolutionList/ListFilter.tsx
  src/common/SolutionList/SavedSolutionList.tsx
  src/components/Admin/GroupStatistics/GroupStatistics.tsx
  src/components/Follower/FollowerInfo.tsx
  src/components/Follower/Personal/FollowerRecommendCard.tsx
  src/components/Follower/Personal/ParticipatingGroup.tsx
  src/components/GroupDetail/ApplicationModal.tsx
  src/components/GroupDetail/GroupInfo.tsx
  src/components/GroupMember/GroupInfo.tsx
  src/components/MyGroup/ActiveGroups.tsx
  src/components/MyGroup/PersonalGroup.tsx
  src/components/Solution/Header/SolutionHeaderTop.tsx
  src/components/Solution/Level.tsx
  src/components/Solution/List/TempSave.tsx
  src/components/Solve/CodeSpace.tsx
  src/components/Solve/Header/HeaderBottom.tsx
  src/components/Solve/Header/HeaderTop.tsx
  src/page/AdminPage.tsx
  src/page/SolutionPage.tsx
  src/types/Solution/solutionTypes.ts
Labels: 🐠 루밍, 🧬 QA

#184 [ Register ] 남은 로직 연결
  src/Router.tsx
  src/common/Header.tsx
  src/page/LoginLoadingPage.tsx
  src/page/LoginPage.tsx
  src/page/RegisterPage.tsx
Labels: 🐠 루밍, 📋 register

#191 [ Deploy ] Feat/register -> develop merge
  src/Router.tsx
  src/common/Header.tsx
  src/components/Register/NickName.tsx
  src/libs/apis/Register/patchProfile.ts
  src/libs/apis/Register/postNickname.ts
  src/page/LoginLoadingPage.tsx
  src/page/LoginPage.tsx
  src/page/RegisterPage.tsx
  src/types/Register/RegisterType.tsx
Labels: 🐠 루밍, 👨‍🎤 deploy

#187 [ Profile ] api 연결
  src/Router.tsx
  src/common/CommonInput.tsx
  src/common/Header.tsx
  src/components/MyProfile/FollowingList.tsx
  src/components/MyProfile/MyGoal.tsx
  src/components/MyProfile/Profile.tsx
  src/components/MyProfile/ProfileEdit.tsx
  src/components/Profile/NicknameInfo.tsx
  src/libs/apis/MyProfile/deleteUser.ts
  src/libs/apis/MyProfile/getFollowList.ts
  src/libs/apis/MyProfile/getUser.ts
  src/libs/apis/MyProfile/patchGoal.ts
  src/libs/apis/MyProfile/patchUser.ts
  src/libs/apis/MyProfile/postCheckExitNickname.ts
  src/libs/hooks/Follower/useUpdateFollower.ts
  src/libs/hooks/MyProfile/useDeleteUser.ts
  src/libs/hooks/MyProfile/useGetFollowList.ts
  src/libs/hooks/MyProfile/useGetUser.ts
  src/libs/hooks/MyProfile/usePatchGoal.ts
  src/libs/hooks/MyProfile/usePatchUser.ts
  src/libs/hooks/MyProfile/usePostCheckExitNickname.ts
  src/types/CommonInput/inputType.ts
  src/types/MyProfile/MyProfileType.tsx
  src/types/Profile/ProfileType.tsx
Labels: 🐠 루밍, 🚀 api, ☁️ react-query, profile

#192 [ Deploy ] Feat/profile -> develop
  src/Router.tsx
  src/assets/icon/ic_minus_white.svg
  src/assets/icon/ic_revise.svg
  src/assets/index.ts
  src/common/CommonButton.tsx
  src/common/CommonInput.tsx
  src/common/Header.tsx
  src/components/MyProfile/FollowingList.tsx
  src/components/MyProfile/MyGoal.tsx
  src/components/MyProfile/Profile.tsx
  src/components/MyProfile/ProfileEdit.tsx
  src/components/Profile/GIthubInfo.tsx
  src/components/Profile/IntroInfo.tsx
  src/components/Profile/LanguageInfo.tsx
  src/components/Profile/NameInfo.tsx
  src/components/Profile/NicknameInfo.tsx
  src/components/Register/SelectBox.tsx
  src/constants/CommonBtn/BtnContent.tsx
  src/libs/apis/MyProfile/deleteUser.ts
  src/libs/apis/MyProfile/getFollowList.ts
  src/libs/apis/MyProfile/getUser.ts
  src/libs/apis/MyProfile/patchGoal.ts
  src/libs/apis/MyProfile/patchUser.ts
  src/libs/apis/MyProfile/postCheckExitNickname.ts
  src/libs/hooks/Follower/useUpdateFollower.ts
  src/libs/hooks/MyProfile/useDeleteUser.ts
  src/libs/hooks/MyProfile/useGetFollowList.ts
  src/libs/hooks/MyProfile/useGetUser.ts
  src/libs/hooks/MyProfile/usePatchGoal.ts
  src/libs/hooks/MyProfile/usePatchUser.ts
  src/libs/hooks/MyProfile/usePostCheckExitNickname.ts
  src/page/MyProfilePage.tsx
  src/styles/style.d.ts
  src/types/CommonInput/inputType.ts
  src/types/MyProfile/MyProfileType.tsx
  src/types/Profile/ProfileType.tsx
Labels: 🐠 루밍, 👨‍🎤 deploy

#193 [ Group-All ] 그룹 뷰 api 연결
  src/assets/index.ts
  src/components/GroupAll/GroupItem.tsx
  src/components/GroupAll/GroupRecommend.tsx
  src/components/GroupAll/TotalCard.tsx
  src/components/GroupAll/groupFilter/LanguageSelectBox.tsx
  src/components/GroupAll/groupFilter/RangeSlidrFilter.tsx
  src/components/GroupAll/groupFilter/SearchBar.tsx
  src/libs/apis/GroupAll/getRoomRecommend.ts
  src/libs/apis/GroupAll/getRoomSearch.ts
  src/libs/apis/GroupAll/getRoomSort.ts
  src/page/GroupAllPage.tsx
Labels: 🐬 문주, 🚀 api, group-all

#198 [ Follower ] 개인뷰 그래프 구현
  src/common/CommonMonthSolve.tsx
  src/components/Follower/FollowerInfo.tsx
  src/components/Follower/Personal/Graph/CustomLabel.tsx
  src/components/Follower/Personal/Graph/SuccessRate.tsx
  src/libs/apis/Home/getMonthSolve.ts
  src/libs/hooks/Home/useGetMonthSolve.ts
  src/page/FollowerPage.tsx
  src/page/Home.tsx
  src/page/SolvePage.tsx
  src/types/Home/getMonthSolveTypes.ts
  src/utils/handleClickGoTopBtn.ts
Labels: 🐠 루밍, 🌭 follower

#200 [ Deploy ] Feat/profile -> develop merge
  src/common/CommonMonthSolve.tsx
  src/components/Follower/FollowerInfo.tsx
  src/components/Follower/Personal/Graph/CustomLabel.tsx
  src/components/Follower/Personal/Graph/SuccessRate.tsx
  src/libs/apis/Home/getMonthSolve.ts
  src/libs/hooks/Home/useGetMonthSolve.ts
  src/page/FollowerPage.tsx
  src/page/Home.tsx
  src/page/SolvePage.tsx
  src/types/Home/getMonthSolveTypes.ts
  src/utils/handleClickGoTopBtn.ts
Labels: 🐠 루밍, 👨‍🎤 deploy

#196 [ QA-5wintaek ] Group 부분 QA 적용
  src/Router.tsx
  src/assets/icon/ic_workbook_white.svg
  src/assets/index.ts
  src/components/GroupCreate/GroupSetting.tsx
  src/components/GroupCreate/ImageSection.tsx
  src/components/GroupCreate/IntroSection.tsx
  src/components/GroupCreate/LanguageSection.tsx
  src/components/GroupCreate/ProgressSection.tsx
  src/components/GroupCreate/TitleSection.tsx
  src/constants/CommonTextarea/textareaConst.ts
  src/constants/Header/HeaderConst.tsx
  src/page/GroupCreate.tsx
Labels: 🐡 승택, 👥 group, 🖼️ publishing, 🧬 QA

#201 [ Qa-5wintaek ] Home 부분 QA 반영
  src/common/CommonMonthSolve.tsx
  src/common/Header.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Home/HomeHeader.tsx
  src/components/Home/TodaySolve.tsx
  src/components/Home/WeekRate.tsx
  src/components/PageLayout/PageLayout.tsx
  src/page/SolvePage.tsx
Labels: 🐡 승택, 🏠 home, 🧬 QA

#203 [ QA-rooming ] qa 2차 반영
  src/common/CommonUserList.tsx
  src/common/Groups.tsx
  src/common/Modal/WarningModal/WarningMoalForm.tsx
  src/common/RecommendCard.tsx
  src/common/SolutionList/ListFilter.tsx
  src/common/SolutionList/SavedSolution.tsx
  src/common/SolutionList/SavedSolutionList.tsx
  src/components/Admin/GroupStatistics/GroupStatistics.tsx
  src/components/Follower/Current/AdditionalProblemsModal.tsx
  src/components/Follower/Current/FollowerFilter.tsx
  src/components/Follower/Personal/FollowerRecommendCard.tsx
  src/components/Follower/Personal/Solutions.tsx
  src/components/Follower/Personal/TotalSolutions.tsx
  src/components/GroupAll/GroupItem.tsx
  src/components/GroupDetail/GroupInfo.tsx
  src/components/MyGroup/PersonalGroup.tsx
  src/components/MyProfile/Profile.tsx
  src/components/PageLayout/PageLayout.tsx
  src/components/Solve/CodeSpace.tsx
  src/components/Solve/Header/CodeSpaceHeader.tsx
  src/components/Solve/Header/HeaderBottom.tsx
  src/components/Solve/Header/PageHeader.tsx
  src/libs/apis/Solution/getMonthlySolution.ts
  src/libs/hooks/Follower/useUpdateFollower.ts
  src/libs/hooks/Solution/useGetMonthlySolution.ts
  src/page/FollowerPage.tsx
  src/page/SolutionListPage.tsx
  src/page/SolvePage.tsx
  src/types/Follower/Current/currentType.ts
  src/types/GroupAll/RecommendCardType.ts
  src/types/Solution/solutionTypes.ts
  src/types/Solve/solveTypes.ts
  src/utils/movePagePosition.ts
  src/utils/removeSavedPage.ts
Labels: 🐠 루밍, 🧬 QA

#204 [ Deploy ] Feat/qa rooming -> develop merge
  src/assets/btn/btn_heart.svg
  src/assets/icon/ic_calendar.svg
  src/assets/index.ts
  src/common/CodeSpace/Memo.tsx
  src/common/CommonUserList.tsx
  src/common/Groups.tsx
  src/common/Modal/WarningModal/WarningMoalForm.tsx
  src/common/RecommendCard.tsx
  src/common/SolutionList/ListFilter.tsx
  src/common/SolutionList/SavedSolution.tsx
  src/common/SolutionList/SavedSolutionList.tsx
  src/components/Admin/GroupStatistics/GroupStatistics.tsx
  src/components/Follower/Current/AdditionalProblemsModal.tsx
  src/components/Follower/Current/FollowerFilter.tsx
  src/components/Follower/FollowerInfo.tsx
  src/components/Follower/Personal/FollowerRecommendCard.tsx
  src/components/Follower/Personal/ParticipatingGroup.tsx
  src/components/Follower/Personal/Solutions.tsx
  src/components/Follower/Personal/TotalSolutions.tsx
  src/components/GroupAll/GroupItem.tsx
  src/components/GroupDetail/ApplicationModal.tsx
  src/components/GroupDetail/GroupInfo.tsx
  src/components/GroupMember/GroupInfo.tsx
  src/components/MyGroup/ActiveGroups.tsx
  src/components/MyGroup/PersonalGroup.tsx
  src/components/MyProfile/Profile.tsx
  src/components/PageLayout/PageLayout.tsx
  src/components/Solution/Header/SolutionHeaderTop.tsx
  src/components/Solution/Level.tsx
  src/components/Solution/List/TempSave.tsx
  src/components/Solve/CodeSpace.tsx
  src/components/Solve/Header/CodeSpaceHeader.tsx
  src/components/Solve/Header/HeaderBottom.tsx
  src/components/Solve/Header/HeaderTop.tsx
  src/components/Solve/Header/PageHeader.tsx
  src/libs/apis/Solution/getMonthlySolution.ts
  src/libs/hooks/Follower/useUpdateFollower.ts
  src/libs/hooks/Solution/useGetMonthlySolution.ts
  src/page/AdminPage.tsx
  src/page/FollowerPage.tsx
  src/page/SolutionListPage.tsx
  src/page/SolutionPage.tsx
  src/page/SolvePage.tsx
  src/types/Follower/Current/currentType.ts
  src/types/GroupAll/RecommendCardType.ts
  src/types/Solution/solutionTypes.ts
  src/types/Solve/solveTypes.ts
  src/utils/movePagePosition.ts
  src/utils/removeSavedPage.ts
Labels: 🐠 루밍, 👨‍🎤 deploy

#206 [ Hotfix ] gnb 구현 및 solution 페이지 접근 안되는 이슈 해결
  src/common/Gnb.tsx
  src/common/Header.tsx
  src/components/PageLayout/PageLayout.tsx
  src/page/SolutionListPage.tsx
Labels: 🐠 루밍, 🚨 hotfix

#207 [ Hotfix ] 각종 에러 핸들링 모달 구현
  src/common/CommonUserList.tsx
  src/common/Modal/ErrorModal/ErrorModalForm.tsx
  src/common/Modal/Modal.tsx
  src/common/Modal/SaveModalForm.tsx
  src/components/Admin/GroupStatistics/GroupStatus.tsx
  src/components/Follower/FollowerInfo.tsx
  src/components/Follower/Personal/FollowerRecommendCard.tsx
  src/components/MyGroup/ActiveGroups.tsx
  src/components/MyProfile/FollowingList.tsx
  src/components/MyProfile/MyGoal.tsx
  src/components/MyProfile/ProfileEdit.tsx
  src/components/Solution/Header/SolutionHeaderTop.tsx
  src/components/Solve/Header/PageHeader.tsx
  src/libs/hooks/Admin/useDeleteMember.ts
  src/libs/hooks/Admin/usePatchApprove.ts
  src/libs/hooks/Admin/usePatchRoomStatus.ts
  src/libs/hooks/Follower/useUpdateFollower.ts
  src/libs/hooks/GroupDetail/usePostPublicRequest.ts
  src/libs/hooks/MyProfile/useDeleteUser.ts
  src/libs/hooks/MyProfile/usePatchGoal.ts
  src/libs/hooks/MyProfile/usePatchUser.ts
  src/libs/hooks/Solution/useDeleteRecords.ts
  src/libs/hooks/Solve/usePatchRecords.ts
  src/libs/hooks/Solve/usePostRecords.ts
  src/libs/hooks/Solve/usePostTempRecords.ts
  src/page/GroupDetail.tsx
  src/page/LoginLoadingPage.tsx
  src/types/Modal/modalType.ts
  src/types/Solve/solveTypes.ts
Labels: 🐠 루밍, 🚨 hotfix

#208 [ Hotfix ] 빠르게 반영해야 하는 부분 수정
  src/common/RecommendCard.tsx
  src/components/GroupDetail/GroupInfo.tsx
  src/components/GroupDetail/Header.tsx
  src/components/GroupMember/GroupInfo.tsx
  src/constants/utils/allTag.ts
  src/libs/apis/GroupDetail/postPublicRequest.ts
  src/libs/hooks/GroupDetail/usePostPublicRequest.ts
  src/page/GroupDetail.tsx
Labels: 🐠 루밍, 🚨 hotfix

#209 [ Hotfix ] 빠르게 수정해야 하는 QA 내용 반영
  src/common/CommonMonthSolve.tsx
  src/common/CommonUserList.tsx
  src/common/Header.tsx
  src/common/InformationTooltip.tsx
  src/common/Modal/ErrorModal/ErrorModalForm.tsx
  src/common/Modal/SaveCheckModal/SaveCheckModal.tsx
  src/common/Modal/SaveCheckModal/SaveCheckModalForm.tsx
  src/common/Modal/WarningModal/WarningMoalForm.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Follower/Current/AdditionalProblemsModal.tsx
  src/components/Follower/Current/NumOfQuestions.tsx
  src/components/Follower/FollowerInfo.tsx
  src/components/Follower/Personal/FollowerRecommendCard.tsx
  src/components/Follower/Personal/ParticipatingGroup.tsx
  src/libs/hooks/Admin/useDeleteMember.ts
  src/types/CommonUserList/userListType.ts
Labels: 🐠 루밍, 🚨 hotfix

#210 [ My Profile ] 내 프로필 수정
  src/components/MyProfile/FollowingList.tsx
  src/components/MyProfile/MyGoal.tsx
  src/components/MyProfile/Profile.tsx
  src/components/MyProfile/ProfileEdit.tsx
  src/components/Profile/GIthubInfo.tsx
Labels: 🔨 fix, 🚨 hotfix, profile

#213 [ Hotfix ] QA 반영
  package.json
  src/assets/index.ts
  src/assets/lottie/lottie.json
  src/assets/test_weekboard_status.svg
  src/common/Header.tsx
  src/common/Modal/ErrorModal/ErrorModalForm.tsx
  src/common/Modal/LinkCopyModalForm.tsx
  src/common/Modal/Modal.tsx
  src/common/Modal/SaveCheckModal/SaveCheckModalForm.tsx
  src/common/Modal/SaveModalForm.tsx
  src/common/Modal/WarningModal/WarningMoalForm.tsx
  src/common/SolutionList/SavedSolution.tsx
  src/common/SolutionList/SavedSolutionList.tsx
  src/components/Admin/GroupStatistics/NumOfMembers.tsx
  src/components/Admin/GroupStatistics/Tooltip.tsx
  src/components/Follower/Current/AdditionalProblemsModal.tsx
  src/components/Follower/Current/CustomTooltip.tsx
  src/components/Follower/Current/EmptyFollower.tsx
  src/components/Follower/Current/FollowerCurrentGraph.tsx
  src/components/Follower/Current/TodaysSolver.tsx
  src/components/Follower/Current/WeeklyCurrentGraph.tsx
  src/components/Follower/Personal/Solutions.tsx
  src/components/Follower/Personal/TotalSolutions.tsx
  src/components/GroupMember/GroupInfo.tsx
  src/components/Solution/Header/SolutionHeaderTop.tsx
  src/libs/apis/Follower/getUserProfile.ts
  src/libs/hooks/Follower/useGetUserProfile.ts
  src/libs/hooks/Solution/useGetRecords.ts
  src/page/FollowerCurrentPage.tsx
  src/page/FollowerPage.tsx
  src/page/LoadingPage.tsx
  src/page/LoginLoadingPage.tsx
  src/page/SolutionPage.tsx
  src/types/Solution/solutionTypes.ts
  src/utils/updateWeek.ts
  yarn.lock
Labels: 🐠 루밍, 🚨 hotfix

#214 [ Hotfix ] 프로필 gnb 구현(로그아웃) 및 유효하지 않은 url 접근 제한
  src/common/Gnb.tsx
  src/common/Header.tsx
  src/common/Modal/ErrorModal/ErrorModal.tsx
  src/common/Modal/ErrorModal/ErrorModalForm.tsx
  src/page/LoginLoadingPage.tsx
  src/page/MyProfilePage.tsx
Labels: 🐠 루밍, 🚨 hotfix

#215 [ Hotfix ] 파비콘 추가 및 토큰 만료 에러 해결
  index.html
  logo.png
  src/libs/api.ts
Labels: 🐠 루밍, 🚨 hotfix

#216 [ QA ] 빠르게 변경해야할 스타일 수정
  src/common/CommonMonthSolve.tsx
  src/common/Header.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Home/HomeHeader.tsx
  src/components/Home/TodaySolve.tsx
  src/components/Home/WeekRate.tsx
Labels: 🐡 승택, 🏠 home, 🧬 QA

#217 [ HotFix ] Home 뷰 빠르게 수정해야할 QA부분
  src/common/CommonMonthSolve.tsx
  src/components/Home/HomeHeader.tsx
  src/components/Home/WeekFollowing/ProfileCard.tsx
  src/components/Home/WeekFollowing/WeeklyFollower.tsx
  src/components/Home/WeekRate.tsx
Labels: 🐡 승택, 🏠 home, 🚨 hotfix

#218 [ QA ] 그룹 뷰 QA 부분 빠르게 수정해야할 부분
  src/assets/btn/btn_link_white.svg
  src/assets/index.ts
  src/common/CommonButton.tsx
  src/components/GroupCreate/GroupSetting.tsx
  src/components/GroupCreate/ImageSection.tsx
  src/components/Home/WeekRate.tsx
  src/constants/CommonBtn/BtnContent.tsx
  src/page/GroupComplete.tsx
  src/page/GroupCreate.tsx
  src/types/GroupCreate/GroupCreateType.tsx
Labels: 🐡 승택, 👥 group, 🚨 hotfix

#219 [ Hotfix ] 그룹 멤버 관련 api 수정, 리프레시 토큰 만료 시 발생하는 에러 해결
  src/components/Follower/Current/FollowerFilter.tsx
  src/libs/api.ts
  src/libs/apis/Follower/getFollowerSummary.ts
Labels: 🐠 루밍, 🚨 hotfix

#220 [ HotFix ] 홈 뷰 빠르게 수정해야할 부분 반영
  src/common/CommonMonthSolve.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/CustomCalendar.tsx
  src/components/Home/HomeHeader.tsx
  src/components/Home/TodaySolve.tsx
Labels: 🐡 승택, 🏠 home, 🚨 hotfix

#222 [ Hotfix ] 에러 해결 및 ux 개선
  src/common/CommonUserList.tsx
  src/common/Modal/ErrorModal/ErrorModalForm.tsx
  src/components/Admin/GroupStatistics/GroupStatistics.tsx
  src/components/Follower/Personal/TotalSolutions.tsx
  src/components/GroupDetail/GroupInfo.tsx
  src/components/MyProfile/Profile.tsx
  src/components/Solution/Header/SolutionHeaderTop.tsx
  src/components/Solve/Header/HeaderBottom.tsx
  src/components/Solve/Header/PageHeader.tsx
  src/libs/hooks/Follower/useGetUserProfile.ts
  src/page/FollowerPage.tsx
Labels: 🐠 루밍, 🚨 hotfix

#223 [ Hotfix ] 용량이 너무 큰 svg를 png로 대체
  src/assets/icon/ic_top3_members.svg
  src/assets/index.ts
  src/components/GroupMember/Top3Members.tsx
  top3member.png
Labels: 🐠 루밍, 🚨 hotfix

#225 [ HotFix ] QA 빠르게 반영해야할 스타일 부분
  src/common/CommonButton.tsx
  src/common/CommonInput.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Home/TodaySolve.tsx
  src/page/GroupComplete.tsx
  src/page/Home.tsx
Labels: 🐡 승택, 🚨 hotfix

#226 [ Deploy ] 불필요한 코드 삭제 및 그룹 신청/ 생성 분기처리
  src/common/CommonButton.tsx
  src/common/CommonInput.tsx
  src/common/Header.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Home/TodaySolve.tsx
  src/libs/api.ts
  src/page/GroupComplete.tsx
  src/page/Home.tsx
Labels: 🐠 루밍, 👨‍🎤 deploy

#229 [ Hotfix ] 빠르게 수정해야 하는 QA 내용 반영
  src/common/CommonButton.tsx
  src/common/CommonInput.tsx
  src/common/CommonTextarea.tsx
  src/common/RecommendCard.tsx
  src/components/GroupAll/groupFilter/LanguageSelectBox.tsx
  src/components/GroupCreate/GroupSetting.tsx
  src/components/GroupCreate/ImageSection.tsx
  src/components/GroupCreate/LanguageSection.tsx
  src/components/MyGroup/ActiveGroups.tsx
  src/components/MyProfile/FollowingList.tsx
  src/components/MyProfile/MyGoal.tsx
  src/components/MyProfile/Profile.tsx
  src/components/Profile/NicknameInfo.tsx
  src/components/Register/IntroInput.tsx
  src/components/Register/NickName.tsx
  src/components/Register/Select.tsx
  src/page/GroupCreate.tsx
  src/page/LoginPage.tsx
  src/utils/handleInput.ts
Labels: 🚨 hotfix

#231 [ 3차QA ] 빠르게 수정해야 하는 QA 내용 반영
  src/assets/icon/ic_graph_workbook.svg
  src/assets/index.ts
  src/common/CodeSpace/CodeEditor.tsx
  src/common/CommonMonthSolve.tsx
  src/common/Gnb.tsx
  src/common/Header.tsx
  src/components/Follower/Current/EmptyFollower.tsx
  src/components/Follower/Personal/ParticipatingGroup.tsx
  src/components/Home/HomeHeader.tsx
  src/components/Home/TodaySolve.tsx
  src/components/Home/WeekFollowing/ProfileCard.tsx
  src/components/Home/WeekRate.tsx
  src/components/Solution/Header/SolutionHeaderTop.tsx
  src/styles/style.d.ts
  src/styles/theme.ts
Labels: 🐡 승택, 🚨 hotfix, 🧬 QA

#232 [ Deploy ] develop -> main merge
  src/assets/icon/ic_graph_workbook.svg
  src/assets/index.ts
  src/common/CodeSpace/CodeEditor.tsx
  src/common/CommonMonthSolve.tsx
  src/common/Gnb.tsx
  src/common/Header.tsx
  src/components/Follower/Current/EmptyFollower.tsx
  src/components/Follower/Personal/ParticipatingGroup.tsx
  src/components/Home/HomeHeader.tsx
  src/components/Home/TodaySolve.tsx
  src/components/Home/WeekFollowing/ProfileCard.tsx
  src/components/Home/WeekRate.tsx
  src/components/Solution/Header/SolutionHeaderTop.tsx
  src/styles/style.d.ts
  src/styles/theme.ts
Labels: 🐡 승택, 👨‍🎤 deploy
