Repository Co-Drive/Driver-Client, pull requests merged in 2024-11, with the labels that each got.

#273 [ QA ] QA 3차 반영
  src/common/AlarmModal.tsx
  src/common/CommonMonthSolve.tsx
  src/common/Header.tsx
  src/common/SolutionList/SavedSolution.tsx
  src/components/Follower/Current/Solver.tsx
  src/components/Follower/Current/TodaysSolver.tsx
  src/components/Follower/Personal/FollowerRecommendCard.tsx
  src/components/Follower/Personal/Solutions.tsx
  src/components/Home/HomeHeader.tsx
  src/components/Home/TodaySolve.tsx
  src/components/Home/WeekFollowing/ProfileCard.tsx
  src/components/Home/WeekRate.tsx
  src/components/Solution/Header/SolutionHeaderTop.tsx
  src/libs/hooks/Alarm/usePostAlarmRead.ts
  src/page/FollowerCurrentPage.tsx
  src/page/GroupComplete.tsx
  src/styles/theme.ts
  src/types/Follower/Current/currentType.ts
Labels: 🐡 승택, 🧬 QA

#274 [Deploy] develop -> main
  src/common/AlarmModal.tsx
  src/common/CommonMonthSolve.tsx
  src/common/Header.tsx
  src/common/SolutionList/SavedSolution.tsx
  src/components/Follower/Current/Solver.tsx
  src/components/Follower/Current/TodaysSolver.tsx
  src/components/Follower/Personal/FollowerRecommendCard.tsx
  src/components/Follower/Personal/Solutions.tsx
  src/components/Home/HomeHeader.tsx
  src/components/Home/TodaySolve.tsx
  src/components/Home/WeekFollowing/ProfileCard.tsx
  src/components/Home/WeekRate.tsx
  src/components/Solution/Header/SolutionHeaderTop.tsx
  src/libs/hooks/Alarm/usePostAlarmRead.ts
  src/page/FollowerCurrentPage.tsx
  src/page/GroupComplete.tsx
  src/styles/theme.ts
  src/types/Follower/Current/currentType.ts
Labels: 👨‍🎤 deploy

#272 [ QA ] 3차 qa 반영
  src/common/Modal/SaveModalForm.tsx
  src/components/Solution/Header/SolutionHeaderTop.tsx
  src/components/Solve/Header/SolveToolTip.tsx
  src/page/SolutionPage.tsx
Labels: 🐠 루밍, 🧬 QA

#275 [ Deploy ] Develop -> main merge
  src/common/Modal/SaveModalForm.tsx
  src/components/Solution/Header/SolutionHeaderTop.tsx
  src/components/Solve/Header/SolveToolTip.tsx
  src/page/SolutionPage.tsx
Labels: 🐠 루밍, 👨‍🎤 deploy

#276 [ Hotfix ] 새로운 알림이 없음에도 프로필 사진에 초록색 동그라미 없어지지 않는 이슈 해결
  src/common/Header.tsx
Labels: 🚨 hotfix, 🔔 alarm

#277 [ Deploy ] Develop -> main merge
  src/common/Header.tsx
Labels: 🐠 루밍, 👨‍🎤 deploy

#278 [ QA ] qa 반영 안된 부분 + 추가된 부분 반영
  src/common/CommonButton.tsx
  src/common/CommonUserList.tsx
  src/components/Admin/GroupStatistics/GroupStatus.tsx
  src/components/Admin/GroupStatistics/NumOfLanguages.tsx
  src/components/Admin/GroupStatistics/NumOfMembers.tsx
  src/components/GroupDetail/ApplicationModal.tsx
  src/components/Solution/Header/SolutionHeaderTop.tsx
Labels: 🐠 루밍, 🚨 hotfix, 🧬 QA

#279 [ Deploy ] Develop -> main merge
  src/common/CommonButton.tsx
  src/common/CommonUserList.tsx
  src/components/Admin/GroupStatistics/GroupStatus.tsx
  src/components/Admin/GroupStatistics/NumOfLanguages.tsx
  src/components/Admin/GroupStatistics/NumOfMembers.tsx
  src/components/GroupDetail/ApplicationModal.tsx
  src/components/Solution/Header/SolutionHeaderTop.tsx
Labels: 🐠 루밍, 👨‍🎤 deploy

#283 [ Hotfix ] 이미지 상대경로로 불러와서 이미지 안 뜨는 이슈 해결
  src/assets/img/img_landing7_bg.png
  src/assets/index.ts
  src/components/Landing/Landing1.tsx
  src/components/Landing/Landing10.tsx
  src/components/Landing/Landing11.tsx
  src/components/Landing/Landing2.tsx
  src/components/Landing/Landing3.tsx
  src/components/Landing/Landing4.tsx
  src/components/Landing/Landing5.tsx
  src/components/Landing/Landing6.tsx
  src/components/Landing/Landing7.tsx
  src/components/Landing/Landing8.tsx
  src/components/Landing/Landing9.tsx
Labels: 🚨 hotfix

#284 [ Deploy ] Develop -> main merge
  src/assets/img/img_landing7_bg.png
  src/assets/index.ts
  src/components/Landing/Landing1.tsx
  src/components/Landing/Landing10.tsx
  src/components/Landing/Landing11.tsx
  src/components/Landing/Landing2.tsx
  src/components/Landing/Landing3.tsx
  src/components/Landing/Landing4.tsx
  src/components/Landing/Landing5.tsx
  src/components/Landing/Landing6.tsx
  src/components/Landing/Landing7.tsx
  src/components/Landing/Landing8.tsx
  src/components/Landing/Landing9.tsx
Labels: 👨‍🎤 deploy

#286 [ Hotfix ] 기존 로직과 다르게 동작하는 부분 수정
  src/common/AlarmModal.tsx
  src/components/Follower/Personal/FollowerRecommendCard.tsx
  src/components/GroupDetail/ApplicationModal.tsx
  src/libs/hooks/Admin/useGetParticipantsList.ts
  src/libs/hooks/Admin/useGetRoomInfo.ts
  src/libs/hooks/Alarm/usePostAlarmRead.ts
  src/libs/hooks/Follower/useGetUserProfile.ts
  src/libs/hooks/GroupDetail/useGetDetail.ts
  src/libs/hooks/GroupMember/useGetMemberList.ts
  src/libs/hooks/GroupMember/useGetRanking.ts
  src/page/FollowerCurrentPage.tsx
  src/utils/updateWeek.ts
Labels: 🐠 루밍, 🚨 hotfix

#287 [ Deploy ] Develop -> main merge
  src/common/AlarmModal.tsx
  src/components/Follower/Personal/FollowerRecommendCard.tsx
  src/components/GroupDetail/ApplicationModal.tsx
  src/libs/hooks/Admin/useGetParticipantsList.ts
  src/libs/hooks/Admin/useGetRoomInfo.ts
  src/libs/hooks/Alarm/usePostAlarmRead.ts
  src/libs/hooks/Follower/useGetUserProfile.ts
  src/libs/hooks/GroupDetail/useGetDetail.ts
  src/libs/hooks/GroupMember/useGetMemberList.ts
  src/libs/hooks/GroupMember/useGetRanking.ts
  src/page/FollowerCurrentPage.tsx
  src/utils/updateWeek.ts
Labels: 🐠 루밍, 👨‍🎤 deploy

#289 [ Hotfix ] 변경된 로직 반영 + 새롭게 발견한 이슈 수정
  src/common/CommonUserList.tsx
  src/common/SolutionList/ListFilter.tsx
  src/common/SolutionList/SavedSolutionList.tsx
  src/components/Calendar/Calendar.tsx
  src/libs/apis/Solution/getMonthlySolution.ts
  src/libs/apis/Solution/getUnsolvedMonths.ts
  src/libs/hooks/Solution/useGetMonthlySolution.ts
  src/libs/hooks/Solution/useGetUnsolvedMonths.ts
  src/types/Solution/solutionTypes.ts
Labels: 🐠 루밍, 🌭 follower, 🚨 hotfix

#290 [ Deploy ] Develop -> main merge
  src/common/CommonUserList.tsx
  src/common/SolutionList/ListFilter.tsx
  src/common/SolutionList/SavedSolutionList.tsx
  src/components/Calendar/Calendar.tsx
  src/libs/apis/Solution/getMonthlySolution.ts
  src/libs/apis/Solution/getUnsolvedMonths.ts
  src/libs/hooks/Solution/useGetMonthlySolution.ts
  src/libs/hooks/Solution/useGetUnsolvedMonths.ts
  src/types/Solution/solutionTypes.ts
Labels: 🐠 루밍, 👨‍🎤 deploy

#292 [ Hotfix ] 이미지 깨짐 이슈 + 한 페이지 스크롤 구현
  src/assets/landing/Landing_group_img.png
  src/assets/landing/landing_codrive_img.png
  src/assets/landing/landing_github_info_img.png
  src/assets/landing/landing_home_img.png
  src/assets/landing/landing_real_img.png
  src/assets/landing/landing_solve_level.png
  src/assets/landing/recruit1.png
  src/assets/landing/recruit10.png
  src/assets/landing/recruit11.png
  src/assets/landing/recruit12.png
  src/assets/landing/recruit13.png
  src/assets/landing/recruit14.png
  src/assets/landing/recruit15.png
  src/assets/landing/recruit16.png
  src/assets/landing/recruit2.png
  src/assets/landing/recruit3.png
  src/assets/landing/recruit4.png
  src/assets/landing/recruit5.png
  src/assets/landing/recruit6.png
  src/assets/landing/recruit7.png
  src/assets/landing/recruit8.png
  src/assets/landing/recruit9.png
  src/components/Landing/Landing3.tsx
  src/components/Landing/Landing4.tsx
  src/components/Landing/Landing5.tsx
  src/components/Landing/Landing7.tsx
  src/components/Landing/Landing9.tsx
  src/page/LandingPage.tsx
Labels: 🐬 문주, 🚨 hotfix, 🎈 Landing

#294 [ Hotfix ] 랜딩페이지 라우팅 및 디자인 QA 반영
  src/Router.tsx
  src/common/Header.tsx
  src/components/Landing/Landing1.tsx
  src/components/Landing/Landing11.tsx
  src/components/Landing/Landing4.tsx
  src/components/PageLayout/PageLayout.tsx
  src/libs/hooks/SSE/useDeleteNotification.ts
  src/page/Home.tsx
  src/page/LandingPage.tsx
  src/page/LoginPage.tsx
Labels: 🐠 루밍, 🎈 Landing

#295 [ Deploy ] Develop -> main merge
  src/Router.tsx
  src/assets/landing/Landing_group_img.png
  src/assets/landing/landing_codrive_img.png
  src/assets/landing/landing_github_info_img.png
  src/assets/landing/landing_home_img.png
  src/assets/landing/landing_real_img.png
  src/assets/landing/landing_solve_level.png
  src/assets/landing/recruit1.png
  src/assets/landing/recruit10.png
  src/assets/landing/recruit11.png
  src/assets/landing/recruit12.png
  src/assets/landing/recruit13.png
  src/assets/landing/recruit14.png
  src/assets/landing/recruit15.png
  src/assets/landing/recruit16.png
  src/assets/landing/recruit2.png
  src/assets/landing/recruit3.png
  src/assets/landing/recruit4.png
  src/assets/landing/recruit5.png
  src/assets/landing/recruit6.png
  src/assets/landing/recruit7.png
  src/assets/landing/recruit8.png
  src/assets/landing/recruit9.png
  src/common/Header.tsx
  src/components/Landing/Landing1.tsx
  src/components/Landing/Landing11.tsx
  src/components/Landing/Landing3.tsx
  src/components/Landing/Landing4.tsx
  src/components/Landing/Landing5.tsx
  src/components/Landing/Landing7.tsx
  src/components/Landing/Landing9.tsx
  src/components/PageLayout/PageLayout.tsx
  src/libs/hooks/SSE/useDeleteNotification.ts
  src/page/Home.tsx
  src/page/LandingPage.tsx
  src/page/LoginPage.tsx
Labels: 🐠 루밍, 👨‍🎤 deploy

#298 [ Landing ] 랜딩페이지 전체적으로 스타일 수정
  src/components/Landing/Landing10.tsx
  src/components/Landing/Landing11.tsx
  src/components/Landing/Landing2.tsx
  src/components/Landing/Landing3.tsx
  src/components/Landing/Landing4.tsx
  src/components/Landing/Landing5.tsx
  src/components/Landing/Landing6.tsx
  src/components/Landing/Landing7.tsx
  src/components/Landing/Landing8.tsx
  src/components/Landing/Landing9.tsx
Labels: 🐬 문주, 🚨 hotfix, 🎈 Landing

#299 [ Deploy ] Develop -> main merge
  src/components/Landing/Landing10.tsx
  src/components/Landing/Landing11.tsx
  src/components/Landing/Landing2.tsx
  src/components/Landing/Landing3.tsx
  src/components/Landing/Landing4.tsx
  src/components/Landing/Landing5.tsx
  src/components/Landing/Landing6.tsx
  src/components/Landing/Landing7.tsx
  src/components/Landing/Landing8.tsx
  src/components/Landing/Landing9.tsx
Labels: 🐬 문주, 👨‍🎤 deploy, 🎈 Landing

#300 [ Hotfix ] 랜딩페이지 내부 컴포넌트 전환 및 애니메이션 적용
  package.json
  src/components/Landing/Landing1.tsx
  src/components/Landing/Landing3.tsx
  src/components/Landing/Landing6.tsx
  src/components/Landing/Landing7.tsx
  src/components/MyProfile/FollowingList.tsx
  src/page/LandingPage.tsx
  yarn.lock
Labels: 🐠 루밍, 🎈 Landing

#301 [ Deploy ] Develop -> main merge
  package.json
  src/components/Landing/Landing1.tsx
  src/components/Landing/Landing3.tsx
  src/components/Landing/Landing6.tsx
  src/components/Landing/Landing7.tsx
  src/components/MyProfile/FollowingList.tsx
  src/page/LandingPage.tsx
  yarn.lock
Labels: 🐠 루밍, 👨‍🎤 deploy

#303 [ Hotfix ] GroupEdit 뷰 데이터 로딩 완료 후 초기값 이슈, ALL 태그 다른게 들어오는 부분 이슈 해결
  src/components/GroupCreate/LanguageSection.tsx
  src/constants/GroupCreate/LanguageConst.tsx
  src/libs/hooks/GroupEdit/usePatchRooms.ts
  src/page/GroupEdit.tsx
Labels: 🐬 문주, 👥 group, 🚨 hotfix

#307 [ Hotfix ] 연속으로 버튼 클릭 시, 연속으로 등록되지 않도록 수정
  src/common/AlarmModal.tsx
  src/common/Modal/SaveModalForm.tsx
  src/common/SolutionList/SavedSolution.tsx
  src/components/Solution/List/TempSave.tsx
  src/components/Solve/Header/HeaderBottom.tsx
  src/libs/hooks/GroupCreate/usePostGroup.ts
  src/libs/hooks/utils/ useScrollAnimation.ts
  src/page/FollowerPage.tsx
  src/page/GroupCreate.tsx
  src/page/SolutionPage.tsx
  src/page/SolvePage.tsx
  src/utils/debounce.ts
Labels: 🐠 루밍, 🚨 hotfix

#310 [ Deploy ] Develop -> main merge
  src/assets/icon/ic_footer_email.svg
  src/assets/icon/ic_footer_insta.svg
  src/assets/icon/ic_footer_logo.svg
  src/assets/index.ts
  src/assets/landing/landing_github_info_img.png
  src/common/AlarmModal.tsx
  src/common/Footer.tsx
  src/common/Modal/SaveModalForm.tsx
  src/common/SolutionList/SavedSolution.tsx
  src/components/Home/TodaySolve.tsx
  src/components/Home/WeekFollowing/ProfileCard.tsx
  src/components/Home/WeekRate.tsx
  src/components/PageLayout/PageLayout.tsx
  src/components/Solution/List/TempSave.tsx
  src/components/Solve/Header/HeaderBottom.tsx
  src/libs/api.ts
  src/libs/hooks/GroupCreate/usePostGroup.ts
  src/libs/hooks/utils/useScrollAnimation.ts
  src/page/AdminPage.tsx
  src/page/FollowerCurrentPage.tsx
  src/page/FollowerPage.tsx
  src/page/GroupAllPage.tsx
  src/page/GroupComplete.tsx
  src/page/GroupCreate.tsx
  src/page/GroupDetail.tsx
  src/page/GroupEdit.tsx
  src/page/GroupJoin.tsx
  src/page/GroupMemberPage.tsx
  src/page/Home.tsx
  src/page/LoginPage.tsx
  src/page/MyGroup.tsx
  src/page/MyProfilePage.tsx
  src/page/RegisterPage.tsx
  src/page/SolutionListPage.tsx
  src/page/SolutionPage.tsx
  src/page/SolvePage.tsx
  src/utils/debounce.ts
Labels: 🐬 문주, 👨‍🎤 deploy, 🎊footer

#311 [ Hotfix ] 주간 팔로잉 현황 이슈 해결 + 문제 등록/ 수정 시, 자동 커밋 완료 모달 띄우기
  src/common/CodeSpace/CodeEditor.tsx
  src/common/CodeSpace/Memo.tsx
  src/common/CommonUserList.tsx
  src/common/Modal/SaveCheckModal/SaveCheckModal.tsx
  src/common/Modal/SaveCheckModal/SaveCheckModalForm.tsx
  src/components/Follower/Current/FollowerCurrentGraph.tsx
  src/components/Solve/Header/PageHeader.tsx
  src/libs/apis/Follower/getFollowerSummary.ts
  src/libs/hooks/Solve/usePatchRecords.ts
  src/libs/hooks/Solve/usePostRecords.ts
  src/page/SolutionListPage.tsx
  src/page/SolvePage.tsx
  src/types/Solve/solveTypes.ts
Labels: 🐠 루밍, 🚨 hotfix

#315 [ Deploy ] Develop -> main merge
  src/components/Landing/Landing8.tsx
  src/components/Landing/Landing9.tsx
  src/components/Profile/RepositoriesInfo.tsx
Labels: 🐬 문주, 👨‍🎤 deploy

#317 [ Hotfix ] 레이아웃 깨지는 부분 수정 및 기능 디벨롭
  src/components/Follower/Personal/ParticipatingGroup.tsx
  src/components/GroupAll/GroupItem.tsx
  src/components/PageLayout/PageLayout.tsx
  src/page/SolutionPage.tsx
  src/utils/removeSavedPage.ts
Labels: 🐠 루밍, 🚨 hotfix
