Repository Co-Drive/Driver-Client, pull requests merged in 2024-10, with the labels that each got.

#235 [ QA ] 2차 QA 수정 - 1
  src/assets/icon/ic_level_five.svg
  src/assets/icon/ic_level_four.svg
  src/assets/icon/ic_level_one.svg
  src/assets/icon/ic_level_three.svg
  src/assets/icon/ic_level_two.svg
  src/assets/index.ts
  src/common/RecommendCard.tsx
  src/components/Follower/Personal/ParticipatingGroup.tsx
  src/components/Home/WeekRate.tsx
  src/components/Solve/Header/HeaderTop.tsx
  src/components/Solve/Header/PageHeader.tsx
  src/components/Solve/Header/SolveToolTip.tsx
  src/page/SolutionPage.tsx
Labels: 🐡 승택, 🧬 QA

#237 [ Deploy ] develop -> main merge
  src/assets/icon/ic_level_five.svg
  src/assets/icon/ic_level_four.svg
  src/assets/icon/ic_level_one.svg
  src/assets/icon/ic_level_three.svg
  src/assets/icon/ic_level_two.svg
  src/assets/index.ts
  src/common/CommonButton.tsx
  src/common/RecommendCard.tsx
  src/components/Follower/Personal/ParticipatingGroup.tsx
  src/components/GroupAll/GroupItem.tsx
  src/components/GroupAll/groupFilter/LanguageSelectBox.tsx
  src/components/GroupAll/groupFilter/SearchBar.tsx
  src/components/Home/WeekRate.tsx
  src/components/Solve/Header/HeaderTop.tsx
  src/components/Solve/Header/PageHeader.tsx
  src/components/Solve/Header/SolveToolTip.tsx
  src/libs/apis/GroupAll/getRoomSort.ts
  src/libs/hooks/GroupAll/useGetRoomSort.ts
  src/page/GroupComplete.tsx
  src/page/SolutionPage.tsx
  src/types/GroupAll/GroupAllType.tsx
Labels: 🐬 문주, 👨‍🎤 deploy

#239 [ GroupEdit ] 그룹 수정하기 뷰 퍼블리싱
  src/page/GroupEdit.tsx
Labels: 🐬 문주, 👥 group, 🖼️ publishing

#241 [ QA ] 2차 QA 수정 - 2
  src/components/Calendar/Calendar.tsx
  src/components/Home/HomeHeader.tsx
  src/constants/Solve/SolveConts.ts
  src/page/Home.tsx
Labels: 🐡 승택, 🧬 QA

#242 [ Hotfix ] 플로우 관련 QA 반영
  src/common/CommonMonthSolve.tsx
  src/common/CommonUserList.tsx
  src/common/Header.tsx
  src/common/Modal/Modal.tsx
  src/common/Modal/SaveModalForm.tsx
  src/common/RecommendCard.tsx
  src/common/SolutionList/Calendar.tsx
  src/common/SolutionList/ListFilter.tsx
  src/common/SolutionList/SavedSolutionList.tsx
  src/components/Admin/GroupStatistics/NumOfLanguages.tsx
  src/components/Calendar/CustomCalendar.tsx
  src/components/Follower/Current/CustomTooltip.tsx
  src/components/Follower/Current/FollowerCurrentGraph.tsx
  src/components/Follower/Current/FollowerFilter.tsx
  src/components/Follower/Current/NumOfQuestions.tsx
  src/components/Follower/Current/TodaysSolver.tsx
  src/components/Follower/Current/WeeklyCurrentGraph.tsx
  src/components/Follower/FollowerInfo.tsx
  src/components/Follower/Personal/ParticipatingGroup.tsx
  src/components/Follower/Personal/TotalSolutions.tsx
  src/components/GroupMember/GroupInfo.tsx
  src/components/Solution/Header/SolutionHeaderBottom.tsx
  src/components/Solve/Header/HeaderBottom.tsx
  src/components/Solve/Header/HeaderTop.tsx
  src/components/Solve/Header/PageHeader.tsx
  src/libs/apis/GroupDetail/getGroupId.ts
  src/libs/apis/GroupJoin/postAnswer.ts
  src/libs/apis/Solve/postRecords.ts
  src/libs/apis/Solve/postTempRecords.ts
  src/libs/hooks/GroupDetail/useGetGroupId.ts
  src/libs/hooks/GroupJoin/usePostAnswer.ts
  src/libs/hooks/Solve/usePostRecords.ts
  src/libs/hooks/Solve/usePostTempRecords.ts
  src/page/AdminPage.tsx
  src/page/FollowerCurrentPage.tsx
  src/page/FollowerPage.tsx
  src/page/GroupAllPage.tsx
  src/page/GroupDetail.tsx
  src/page/GroupJoin.tsx
  src/page/Home.tsx
  src/page/LoadingPage.tsx
  src/page/LoginLoadingPage.tsx
  src/page/LoginPage.tsx
  src/page/MyGroup.tsx
  src/page/RegisterPage.tsx
  src/page/SolutionListPage.tsx
  src/page/SolutionPage.tsx
  src/page/SolvePage.tsx
  src/types/Follower/Personal/personalType.ts
  src/types/GroupAll/RecommendCardType.ts
  src/types/GroupJoin/GroupJoinType.ts
  src/types/MyGroup/myGroupType.ts
  src/types/Solution/solutionTypes.ts
  src/types/Solve/solveTypes.ts
Labels: 🚨 hotfix

#243 [ Deploy ] Merge Develop -> Main
  src/common/CommonMonthSolve.tsx
  src/common/CommonUserList.tsx
  src/common/Header.tsx
  src/common/Modal/Modal.tsx
  src/common/Modal/SaveModalForm.tsx
  src/common/RecommendCard.tsx
  src/common/SolutionList/Calendar.tsx
  src/common/SolutionList/ListFilter.tsx
  src/common/SolutionList/SavedSolutionList.tsx
  src/components/Admin/GroupStatistics/NumOfLanguages.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/CustomCalendar.tsx
  src/components/Follower/Current/CustomTooltip.tsx
  src/components/Follower/Current/FollowerCurrentGraph.tsx
  src/components/Follower/Current/FollowerFilter.tsx
  src/components/Follower/Current/NumOfQuestions.tsx
  src/components/Follower/Current/TodaysSolver.tsx
  src/components/Follower/Current/WeeklyCurrentGraph.tsx
  src/components/Follower/FollowerInfo.tsx
  src/components/Follower/Personal/ParticipatingGroup.tsx
  src/components/Follower/Personal/TotalSolutions.tsx
  src/components/GroupMember/GroupInfo.tsx
  src/components/Home/HomeHeader.tsx
  src/components/Solution/Header/SolutionHeaderBottom.tsx
  src/components/Solve/Header/HeaderBottom.tsx
  src/components/Solve/Header/HeaderTop.tsx
  src/components/Solve/Header/PageHeader.tsx
  src/constants/Solve/SolveConts.ts
  src/libs/apis/GroupDetail/getGroupId.ts
  src/libs/apis/GroupJoin/postAnswer.ts
  src/libs/apis/Solve/postRecords.ts
  src/libs/apis/Solve/postTempRecords.ts
  src/libs/hooks/GroupDetail/useGetGroupId.ts
  src/libs/hooks/GroupJoin/usePostAnswer.ts
  src/libs/hooks/Solve/usePostRecords.ts
  src/libs/hooks/Solve/usePostTempRecords.ts
  src/page/AdminPage.tsx
  src/page/FollowerCurrentPage.tsx
  src/page/FollowerPage.tsx
  src/page/GroupAllPage.tsx
  src/page/GroupDetail.tsx
  src/page/GroupJoin.tsx
  src/page/Home.tsx
  src/page/LoadingPage.tsx
  src/page/LoginLoadingPage.tsx
  src/page/LoginPage.tsx
  src/page/MyGroup.tsx
  src/page/RegisterPage.tsx
  src/page/SolutionListPage.tsx
  src/page/SolutionPage.tsx
  src/page/SolvePage.tsx
  src/types/Follower/Personal/personalType.ts
  src/types/GroupAll/RecommendCardType.ts
  src/types/GroupJoin/GroupJoinType.ts
  src/types/MyGroup/myGroupType.ts
  src/types/Solution/solutionTypes.ts
  src/types/Solve/solveTypes.ts
Labels: 🐠 루밍, 🐡 승택, 👨‍🎤 deploy

#244 [ Hotfix ] 모든 에러 해결 및 피그마와 다른 부분 수정
  src/common/CommonUserList.tsx
  src/common/RecommendCard.tsx
  src/components/GroupMember/GroupInfo.tsx
  src/components/MyGroup/PersonalGroup.tsx
  src/components/Solve/Header/HeaderTop.tsx
  src/components/Solve/Header/SolveToolTip.tsx
  src/constants/Solve/SolveTooltipConst.tsx
  src/libs/hooks/GroupJoin/usePostAnswer.ts
  src/libs/hooks/Solution/useGetRecords.ts
  src/libs/hooks/Solve/usePatchRecords.ts
  src/page/GroupJoin.tsx
  src/page/SolvePage.tsx
  src/types/Solve/solveTooltipTypes.ts
Labels: 🐠 루밍, 🚨 hotfix

#245 [ Deploy ] Develop -> Main merge
  src/common/CommonUserList.tsx
  src/common/RecommendCard.tsx
  src/components/GroupMember/GroupInfo.tsx
  src/components/MyGroup/PersonalGroup.tsx
  src/components/Solve/Header/HeaderTop.tsx
  src/components/Solve/Header/SolveToolTip.tsx
  src/constants/Solve/SolveTooltipConst.tsx
  src/libs/hooks/GroupJoin/usePostAnswer.ts
  src/libs/hooks/Solution/useGetRecords.ts
  src/libs/hooks/Solve/usePatchRecords.ts
  src/page/GroupJoin.tsx
  src/page/SolvePage.tsx
  src/types/Solve/solveTooltipTypes.ts
Labels: 🐠 루밍, 👨‍🎤 deploy

#246 Feat/qa 5wintaek
  src/components/Follower/Personal/Graph/CustomToolTip.tsx
  src/components/Follower/Personal/Graph/SuccessRate.tsx
  src/components/Home/TodaySolve.tsx
  src/components/MyProfile/MyGoal.tsx
  src/libs/hooks/MyProfile/usePatchGoal.ts
  src/page/Home.tsx
Labels: 🚨 hotfix, 🧬 QA

#247 [ Deploy ] Merge Develop -> Main
  src/components/Follower/Personal/Graph/CustomToolTip.tsx
  src/components/Follower/Personal/Graph/SuccessRate.tsx
  src/components/Home/TodaySolve.tsx
  src/components/MyProfile/MyGoal.tsx
  src/libs/hooks/MyProfile/usePatchGoal.ts
  src/page/Home.tsx
Labels: 👨‍🎤 deploy

#250 [ Group ] 그룹 멤버 순위 기능 구현
  src/assets/icon/ic_rank_1.svg
  src/assets/icon/ic_rank_2.svg
  src/assets/icon/ic_rank_2_gray.svg
  src/assets/icon/ic_rank_3.svg
  src/assets/icon/ic_rank_3_gray.svg
  src/assets/img/img_empty_profile.png
  src/assets/img/img_ranking_bg.png
  src/assets/index.ts
  src/components/GroupMember/MemberHeader.tsx
  src/components/GroupMember/RankingTooltip.tsx
  src/components/GroupMember/Top3Members.tsx
  src/libs/apis/GroupMember/getRanking.ts
  src/libs/hooks/GroupMember/useGetRanking.ts
  src/page/GroupMemberPage.tsx
  src/types/Admin/memberTypes.ts
Labels: 🐠 루밍, 👥 group, 🖼️ publishing, 🚀 api

#251 [ Deploy ] feat/group -> develop merge
  src/assets/icon/ic_rank_1.svg
  src/assets/icon/ic_rank_2.svg
  src/assets/icon/ic_rank_2_gray.svg
  src/assets/icon/ic_rank_3.svg
  src/assets/icon/ic_rank_3_gray.svg
  src/assets/img/img_empty_profile.png
  src/assets/img/img_ranking_bg.png
  src/assets/index.ts
  src/common/RecommendCard.tsx
  src/components/GroupMember/MemberHeader.tsx
  src/components/GroupMember/RankingTooltip.tsx
  src/components/GroupMember/Top3Members.tsx
  src/libs/apis/GroupMember/getRanking.ts
  src/libs/hooks/GroupMember/useGetRanking.ts
  src/page/GroupEdit.tsx
  src/page/GroupMemberPage.tsx
  src/types/Admin/memberTypes.ts
Labels: 🐠 루밍, 👨‍🎤 deploy

#252 [ Deploy ] develop -> main merge
  src/assets/icon/ic_rank_1.svg
  src/assets/icon/ic_rank_2.svg
  src/assets/icon/ic_rank_2_gray.svg
  src/assets/icon/ic_rank_3.svg
  src/assets/icon/ic_rank_3_gray.svg
  src/assets/img/img_empty_profile.png
  src/assets/img/img_ranking_bg.png
  src/assets/index.ts
  src/common/RecommendCard.tsx
  src/components/GroupMember/MemberHeader.tsx
  src/components/GroupMember/RankingTooltip.tsx
  src/components/GroupMember/Top3Members.tsx
  src/libs/apis/GroupMember/getRanking.ts
  src/libs/hooks/GroupMember/useGetRanking.ts
  src/page/GroupEdit.tsx
  src/page/GroupMemberPage.tsx
  src/types/Admin/memberTypes.ts
Labels: 🐠 루밍, 👨‍🎤 deploy

#253 [ Alarm ] 알람 퍼블리싱 뷰
  src/common/AlarmModal.tsx
  src/common/Gnb.tsx
  src/common/Header.tsx
  src/constants/Alarm/alarm.ts
  src/types/Alarm/alarmType.ts
Labels: 🐡 승택, 🖼️ publishing

#255 [ GroupEdit ] 그룹 수정하기 뷰 api 연결
  src/Router.tsx
  src/common/CommonInput.tsx
  src/components/GroupCreate/IntroSection.tsx
  src/components/GroupCreate/LanguageSection.tsx
  src/components/GroupCreate/ProgressSection.tsx
  src/components/GroupMember/GroupInfo.tsx
  src/libs/apis/GroupEdit/getRoomsId.ts
  src/libs/apis/GroupEdit/patchRooms.ts
  src/libs/hooks/GroupEdit/useGetRoomsId.ts
  src/libs/hooks/GroupEdit/usePatchRooms.ts
  src/page/GroupEdit.tsx
Labels: 🐬 문주, 👥 group, 🚀 api

#254 [ GroupAll ] All 태그 눌렀을 시 그룹 렌더링 안되는 부분 수정
  src/components/GroupAll/GroupItem.tsx
  src/types/GroupItem/groupItemType.ts
Labels: 🚨 hotfix, group-all

#262 [ Alarm ] API 연결
  src/assets/icon/ic_new_alarm.svg
  src/assets/index.ts
  src/common/AlarmModal.tsx
  src/common/Header.tsx
  src/libs/apis/Alarm/getAlarmList.ts
  src/libs/apis/Alarm/postAlarmRead.ts
  src/libs/hooks/Alarm/useGetAlarmList.ts
  src/libs/hooks/Alarm/usePostAlarmRead.ts
  src/types/Alarm/alarmType.ts
Labels: 🐡 승택, 🚀 api, 🔔 alarm

#266 [ deploy ] feat/Modal -> develop
  src/assets/icon/ic_new_alarm.svg
  src/assets/index.ts
  src/common/AlarmModal.tsx
  src/common/Header.tsx
  src/libs/apis/Alarm/getAlarmList.ts
  src/libs/apis/Alarm/postAlarmRead.ts
  src/libs/hooks/Alarm/useGetAlarmList.ts
  src/libs/hooks/Alarm/usePostAlarmRead.ts
  src/types/Alarm/alarmType.ts
Labels: 👨‍🎤 deploy

#261 [ Alarm ] 일림 기능을 위한 SSE 연결
  package.json
  src/App.tsx
  src/common/AlarmModal.tsx
  src/common/CommonUserList.tsx
  src/common/Gnb.tsx
  src/common/Header.tsx
  src/components/Solution/List/TempSave.tsx
  src/libs/apis/SSE/deleteNotification.ts
  src/libs/hooks/Alarm/useGetAlarmList.ts
  src/libs/hooks/SSE/useDeleteNotification.ts
  src/libs/hooks/SSE/useGetSessionStorage.ts
  src/libs/hooks/Solution/useGetTempRecords.ts
  src/libs/hooks/Solve/usePostRecords.ts
  src/libs/hooks/Solve/usePostTempRecords.ts
  src/page/SolvePage.tsx
Labels: 🐠 루밍, 🔔 alarm

#267 [ Hotfix ] 문제 푼 사람이 아무도 없는 경우 추가
  src/assets/img/img_rank_bg_none_people.png
  src/assets/index.ts
  src/components/GroupMember/Top3Members.tsx
Labels: 🐠 루밍, 🚨 hotfix

#268 [ Alarm ] 알림 클릭 후 페이지 URL은 변경되지만 화면이 렌더링이 되지 않는 현상 수정
  src/common/AlarmModal.tsx
  src/common/Header.tsx
  yarn.lock
Labels: 🐡 승택, 🚀 api, 🚨 hotfix, 🔔 alarm
