Repository Co-Drive/Driver-Client, pull requests merged in 2024-12, with the labels that each got.

#320 [ Hotfix ] 캘린더 부분 변경사항 수정
  src/components/Calendar/Calendar.tsx
Labels: 🐡 승택, 🏠 home, 🚨 hotfix

#321 [ deploy ] develop -> main 캘린더 수정 사항 merge
  src/components/Calendar/Calendar.tsx
Labels: 🐡 승택, 👨‍🎤 deploy, 🚨 hotfix

#325 [ Refactor ] UT 내용 반영
  .gitignore
  src/App.tsx
  src/Router.tsx
  src/assets/icon/ic_warning_big.svg
  src/assets/index.ts
  src/common/ErrorBoundary.tsx
  src/page/ErrorPage.tsx
  vite.config.ts
Labels: 🐠 루밍

#327 [ Refactor ] 라이팅 수정
  src/common/Modal/SaveModalForm.tsx
  src/components/Landing/Landing4.tsx
Labels: 🐠 루밍

#329 [ Hotfix ] 문제풀이 리스트 수가 지정한 것과 다르게 나오는 이슈 해결
  src/common/SolutionList/SavedSolutionList.tsx
Labels: 🐠 루밍, 🚨 hotfix

#330 [Refactor] 사파리환경에서 CSS 안보이던 현상 수정
  src/common/RecommendCard.tsx
Labels: 🐡 승택, group-all

#332 [ deploy ] develop -> main 머지
  src/common/RecommendCard.tsx
Labels: 👨‍🎤 deploy
