Repository Co-Drive/Driver-Client, pull requests merged in 2025-03, with the labels that each got.

#368 [ SP2 ] 선택된 정렬(최신순 / 가나다순 / 오래된 순)이 뒤로 가기로 돌아왔을 때에도 유지되도록 구현
  src/common/CommonUserList.tsx
  src/common/Gnb.tsx
  src/common/Groups.tsx
  src/common/RecommendCard.tsx
  src/common/SolutionList/ListFilter.tsx
  src/common/SolutionList/SavedSolutionList.tsx
  src/components/Admin/AdminMemberList.tsx
  src/components/Follower/Current/FollowerFilter.tsx
  src/components/Follower/Current/FollowerList.tsx
  src/components/Follower/Personal/ParticipatingGroup.tsx
  src/components/Follower/Personal/Solutions.tsx
  src/components/GroupMember/MemberHeader.tsx
  src/components/GroupMember/MemberList.tsx
  src/components/Home/WeekFollowing/WeeklyFollower.tsx
  src/components/MyGroup/ActiveGroups.tsx
  src/components/MyGroup/PersonalGroup.tsx
  src/libs/apis/Admin/getParticipantsList.ts
  src/libs/apis/Follower/getFollowerSummary.ts
  src/libs/apis/GroupMember/getMeberList.ts
  src/libs/apis/Solution/getMonthlySolution.ts
  src/libs/apis/utils/getRooms.ts
  src/libs/hooks/Alarm/usePostAlarmRead.ts
  src/libs/hooks/GroupEdit/usePatchRooms.ts
  src/libs/hooks/GroupJoin/usePostAnswer.ts
  src/libs/hooks/Solution/useDeleteRecords.ts
  src/libs/hooks/Solve/usePostRecords.ts
  src/libs/hooks/Solve/usePostTempRecords.ts
  src/page/GroupComplete.tsx
  src/page/GroupEdit.tsx
  src/types/Solution/solutionTypes.ts
  src/utils/handleClickPage.ts
Labels: 🐠 루밍, 🚀 SP2

#369 [ SP2 ] 이미지 리사이징
  package.json
  src/components/GroupCreate/ImageSection.tsx
  src/page/GroupCreate.tsx
  src/page/GroupEdit.tsx
  yarn.lock
Labels: 🐬 문주, 🛠️ refactor, 🚀 SP2

#371 [ Deploy ] Develop -> main merge
  package.json
  src/components/GroupCreate/ImageSection.tsx
  src/page/GroupCreate.tsx
  src/page/GroupEdit.tsx
  yarn.lock
Labels: 🐬 문주, 👨‍🎤 deploy
