Repository Co-Drive/Driver-Client, pull requests merged in 2025-01, with the labels that each got.

#334 [ Refactor ] 사용성 개선을 위해 cursor: pointer; 적용
  src/common/CodeSpace/Memo.tsx
  src/components/Solve/Header/HeaderBottom.tsx
  src/components/Solve/Header/HeaderTop.tsx
  src/page/SolvePage.tsx
Labels: 🐠 루밍, 😈 solve

#336 [ Hofix ] 년도가 바꼈을 때 해당 년도에 저장된 문제풀이 정보가 나오지 않는 이슈 해결
  src/common/SolutionList/ListFilter.tsx
  src/common/SolutionList/SavedSolutionList.tsx
  src/components/Calendar/Calendar.tsx
Labels: 🐠 루밍, 🏠 home, 😈 solution, 🚨 hotfix

#340 [ deploy ] develop -> main
  src/components/Calendar/Calendar.tsx
Labels: 🐡 승택, 👨‍🎤 deploy

#343 [ Refactor ] 로그인하지 않은 페이지로 접근 시, 로그인 페이지로 라우팅 (+ 랜딩페이지 주소 변경)
  src/PrivateRoute.tsx
  src/Router.tsx
  src/page/Home.tsx
  src/page/LoginPage.tsx
  src/page/SolutionListPage.tsx
Labels: 🐠 루밍, 🛠️ refactor

#345 [ Hotfix ] 툴팁 추가 + 내 프로필 수정 뷰 스타일 수정
  src/components/GroupCreate/ImageSection.tsx
  src/components/Home/TodaySolve.tsx
  src/components/Home/WeekRate.tsx
  src/components/MyProfile/ProfileEdit.tsx
  src/components/Profile/GIthubInfo.tsx
  src/components/Profile/IntroInfo.tsx
  src/components/Profile/LanguageInfo.tsx
  src/components/Profile/NicknameInfo.tsx
  src/components/Profile/RepositoriesInfo.tsx
  src/components/Register/NickName.tsx
  src/components/Register/Repositories.tsx
  src/page/RegisterPage.tsx
Labels: 🐬 문주, 🚨 hotfix

#346 [ Deploy ] Develop -> main mergeDevelop
  src/components/GroupCreate/ImageSection.tsx
  src/components/Home/TodaySolve.tsx
  src/components/Home/WeekRate.tsx
  src/components/MyProfile/ProfileEdit.tsx
  src/components/Profile/GIthubInfo.tsx
  src/components/Profile/IntroInfo.tsx
  src/components/Profile/LanguageInfo.tsx
  src/components/Profile/NicknameInfo.tsx
  src/components/Profile/RepositoriesInfo.tsx
  src/components/Register/NickName.tsx
  src/components/Register/Repositories.tsx
  src/page/RegisterPage.tsx
Labels: 🐬 문주, 👨‍🎤 deploy

#350 [ Hotfix ] 폰트 정의 방법 수정
  src/common/InformationTooltip.tsx
  src/components/Admin/GroupStatistics/NumOfMembers.tsx
  src/components/GroupAll/GroupRecommend.tsx
  src/components/GroupCreate/ImageSection.tsx
  src/components/Home/TodaySolve.tsx
  src/components/Home/WeekRate.tsx
  src/components/Register/Repositories.tsx
Labels: 🐬 문주, 🚨 hotfix

#351 [ Deploy ] Develop -> main merge
  src/common/InformationTooltip.tsx
  src/components/Admin/GroupStatistics/NumOfMembers.tsx
  src/components/GroupAll/GroupRecommend.tsx
  src/components/GroupCreate/ImageSection.tsx
  src/components/Home/TodaySolve.tsx
  src/components/Home/WeekRate.tsx
  src/components/Register/Repositories.tsx
Labels: 🐬 문주, 👨‍🎤 deploy

#348 [ Refactor ] 툴팁 공통 컴포넌트로 분리
  src/common/DetailTooltip.tsx
  src/components/GroupCreate/ImageSection.tsx
  src/components/Home/WeekRate.tsx
  src/components/Register/Repositories.tsx
Labels: 🐬 문주, 🛠️ refactor

#357 [ SP2 ] 홈 최적화
  img_home_banner.png
  src/Router.tsx
  src/assets/img/img_home_banner.png
  src/components/Home/HomeHeader.tsx
Labels: 🐠 루밍, 🚀 SP2

#358 [ SP2 ] 그룹 뷰 React-Query로 마이그레이션 및 코드정리, 이미지 alt 속성 추가/커서 포인터 추가
  src/common/CommonUserList.tsx
  src/common/Gnb.tsx
  src/common/Header.tsx
  src/common/RecommendCard.tsx
  src/components/Follower/Current/EmptyFollower.tsx
  src/components/Follower/Current/FollowerFilter.tsx
  src/components/Follower/Current/NumOfQuestions.tsx
  src/components/Follower/Current/Solver.tsx
  src/components/Follower/Current/TodaysSolver.tsx
  src/components/Follower/Personal/FollowerRecommendCard.tsx
  src/components/Follower/Personal/ParticipatingGroup.tsx
  src/components/GroupAll/GroupItem.tsx
  src/components/GroupAll/GroupRecommend.tsx
  src/components/GroupCreate/ImageSection.tsx
  src/components/GroupDetail/GroupInfo.tsx
  src/components/GroupMember/GroupInfo.tsx
  src/components/GroupMember/Top3Members.tsx
  src/components/Landing/Landing1.tsx
  src/components/Landing/Landing10.tsx
  src/components/Landing/Landing3.tsx
  src/components/Landing/Landing7.tsx
  src/components/Landing/Landing8.tsx
  src/components/MyGroup/ActiveGroups.tsx
  src/components/MyGroup/PersonalGroup.tsx
  src/components/MyProfile/FollowingList.tsx
  src/components/MyProfile/Profile.tsx
  src/components/Register/Options.tsx
  src/components/Solution/Header/SolutionHeaderTop.tsx
  src/constants/GroupAll/TagsConst.tsx
  src/libs/apis/GroupAll/getRoomRecommend.ts
  src/libs/hooks/GroupAll/useGetRoomRecommend.ts
  src/page/GroupDetail.tsx
Labels: 🐬 문주, ☁️ react-query, 🛠️ refactor, 🚀 SP2

#360 [ Deploy ] Develop -> main merge
  src/common/CommonUserList.tsx
  src/common/Gnb.tsx
  src/common/Header.tsx
  src/common/RecommendCard.tsx
  src/components/Follower/Current/EmptyFollower.tsx
  src/components/Follower/Current/FollowerFilter.tsx
  src/components/Follower/Current/NumOfQuestions.tsx
  src/components/Follower/Current/Solver.tsx
  src/components/Follower/Current/TodaysSolver.tsx
  src/components/Follower/Personal/FollowerRecommendCard.tsx
  src/components/Follower/Personal/ParticipatingGroup.tsx
  src/components/GroupAll/GroupItem.tsx
  src/components/GroupAll/GroupRecommend.tsx
  src/components/GroupCreate/ImageSection.tsx
  src/components/GroupDetail/GroupInfo.tsx
  src/components/GroupMember/GroupInfo.tsx
  src/components/GroupMember/Top3Members.tsx
  src/components/Landing/Landing1.tsx
  src/components/Landing/Landing10.tsx
  src/components/Landing/Landing3.tsx
  src/components/Landing/Landing7.tsx
  src/components/Landing/Landing8.tsx
  src/components/MyGroup/ActiveGroups.tsx
  src/components/MyGroup/PersonalGroup.tsx
  src/components/MyProfile/FollowingList.tsx
  src/components/MyProfile/Profile.tsx
  src/components/Register/Options.tsx
  src/components/Solution/Header/SolutionHeaderTop.tsx
  src/constants/GroupAll/TagsConst.tsx
  src/libs/apis/GroupAll/getRoomRecommend.ts
  src/libs/hooks/GroupAll/useGetRoomRecommend.ts
  src/page/GroupDetail.tsx
Labels: 🐬 문주, 👨‍🎤 deploy

#361 [ SP2 ] 폰트 최적화
  fonts/Montserrat/Montserrat-Medium.ttf
  fonts/Montserrat/Montserrat-Regular.ttf
  fonts/Montserrat/Montserrat-SemiBold.ttf
  fonts/Suit/SUIT-Bold.ttf
  fonts/Suit/SUIT-Light.ttf
  fonts/Suit/SUIT-Medium.ttf
  fonts/Suit/SUIT-Regular.ttf
  fonts/Suit/SUIT-SemiBold.ttf
  index.html
  src/styles/globalStyle.ts
Labels: 🐠 루밍, 🚀 SP2
